USE tiger

-- Account Number

SELECT DBR_CLI_REF_NO AS 'AcctID', 
RIGHT(ADR_NAME, LEN(ADR_NAME) - 1) AS 'Acctnumber'
FROM CDS.DBR INNER JOIN CDS.ADR ON DBR_NO = ADR_DBR_NO
WHERE DBR_CLI_REF_NO IN 
(
'174392857'
) AND ADR_SEQ_NO = 'R2'


-- NAME, SSN, ADDRESS, DOB

SELECT DBR_CLI_REF_NO AS 'AcctID', 
DBR_NAME1 AS 'NAME',
ADR_TAX_ID AS 'SSN',
ADR_ADDR1 AS 'Address',
ADR_ADDR2 AS 'Address2',
ADR_CITY AS 'City',
ADR_STATE AS 'State',
ADR_ZIP_CODE AS 'Zip',
ADR_DOB_O AS 'DateOfBirth'
FROM CDS.DBR INNER JOIN CDS.ADR ON DBR_NO = ADR_DBR_NO
WHERE DBR_CLI_REF_NO IN 
(
'174392857'
) AND ADR_SEQ_NO = '01'


-- 
